version: '3.8'

services:
  # 1. Database
  db:
    image: postgres:15
    container_name: proyecto_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: rastreador_precios
    ports:
      - "5432:5432"

  # 2. Go Backend
  backend:
    image: golang:1.25
    container_name: rastreador_backend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: bash -c "go install github.com/air-verse/air@latest && go mod download && air -c backend/.air.toml"
    depends_on:
      - db

  # 3. React Frontend
  frontend:
    image: node:22
    container_name: rastreador_frontend
    working_dir: /app/frontend
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: bash -c "npm install && npm run dev -- --host"